server:
  port: 3001
spring:
  application:
    name: messageserver
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:3306/tlrs?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #mybatis:
    # mapper-locations: classpath:Mapper/*.xml
    #type-aliases-package: com.example.user.mapper
  #pagehelper
  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.example.chatserver.mapper
